services:
  accounts:
    image: "apurvabhatt/accounts:v1"
    container_name: accounts_ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - apurva
  loans:
    image: "apurvabhatt/loans:v1"
    container_name: loans_ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - apurva
  card:
    image: "apurvabhatt/card:v1"
    container_name: cards_ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - apurva
networks:
  apurva:
    driver: "bridge"